server:
  port: 8880

spring:
  application:
    name: gassman-eureka

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    server:
      waitTimeInMsWhenSyncEmpty: 0